Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices,
along with a collection of mathematical functions to operate on these data structures. In this lesson, we will
cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [4]:
import numpy as np

# Create 1D arrays
array1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", array1)
print(type(array1))
print("Shape of 1D Array:", array1.shape)

1D Array: [1 2 3 4 5]
<class 'numpy.ndarray'>
Shape of 1D Array: (5,)


In [7]:
array2 = np.array([1, 2, 3, 4, 5])
array2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [8]:
## Create 2D arrays
array2 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print("2D Array:\n", array2)
print("Shape of 2D Array:", array2.shape)


2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape of 2D Array: (2, 5)


In [16]:
np.arange(1, 13, 2).reshape(2, 3)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [17]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
## identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
## Attributes of numpy arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(" Array:\n", arr)
print("Shape of Array:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type of elements:", arr.dtype)
print("Size of each element in bytes:", arr.itemsize)
print("Total number of elements:", arr.size)


 Array:
 [[1 2 3]
 [4 5 6]]
Shape of Array: (2, 3)
Number of dimensions: 2
Data type of elements: int64
Size of each element in bytes: 8
Total number of elements: 6


In [22]:
### Numpy vectorized operations

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element-wise addition
add_result = arr1 + arr2
print("Element-wise Addition:", add_result)

# Element-wise multiplication
mul_result = arr1 * arr2
print("Element-wise Multiplication:", mul_result)

# Element-wise substraction
sub_result = arr1 - arr2
print("Element-wise Subtraction:", sub_result)

# Element-wise division
div_result = arr1 / arr2
print("Element-wise Division:", div_result)



Element-wise Addition: [11 22 33 44 55]
Element-wise Multiplication: [ 10  40  90 160 250]
Element-wise Subtraction: [ -9 -18 -27 -36 -45]
Element-wise Division: [0.1 0.1 0.1 0.1 0.1]


In [24]:
## Universal functions (ufuncs)

arr = np.array([1, 4, 9, 16, 25])

# Square root
sqrt_result = np.sqrt(arr)
print("Square Root:", sqrt_result)

# Exponential
exp_result = np.exp(arr)
print("Exponential:", exp_result)

# Sine
sin_result = np.sin(arr)
print("Sine:", sin_result)

# Logarithm
log_result = np.log(arr)
print("Logarithm:", log_result)

Square Root: [1. 2. 3. 4. 5.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Logarithm: [0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [4]:
## Indexing and slicing
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:\n", arr)

# Accessing elements
print("Element at (0, 1):", arr[0, 1])
print("Element at (2, 2):", arr[2, 2])

# Slicing
print("First row:", arr[0, :])
print("Second column:", arr[:, 1])

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (0, 1): 2
Element at (2, 2): 9
First row: [1 2 3]
Second column: [2 5 8]


In [5]:
## Modifying elements

arr[0, 0] = 10
print("Modified Array:\n", arr)

Modified Array:
 [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [6]:
arr[1:] = 100
print("Modified Array:\n", arr)

Modified Array:
 [[ 10   2   3]
 [100 100 100]
 [100 100 100]]


In [7]:
arr[0:] = 10
print("Modified Array:\n", arr)

Modified Array:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
## Statistical functions

## Normalisation - to have a mean of 0 and standard deviation of 1

data = np.array([1, 2, 3, 4, 5])
print("Original Array:", data)

## Calculate mean and standard deviation
mean = np.mean(data)
std = np.std(data)

## Normalize the data
normalized_data = (data - mean) / std
print("Normalized Array:", normalized_data)



Original Array: [1 2 3 4 5]
Normalized Array: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [11]:
## Statistical functions

arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)

mean = np.mean(arr)
print("Mean:", mean)

median = np.median(arr)
print("Median:", median)

standard_deviation = np.std(arr)
print("Standard Deviation:", standard_deviation)

variance = np.var(arr)
print("Variance:", variance)

Original Array: [1 2 3 4 5]
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [13]:
## Logical operations

arr = np.array([1, 2, 3, 4, 5])
print("Original Array:", arr)

greater_than_3 = arr > 3
print("Elements greater than 3:", greater_than_3)

less_than_3 = arr < 3
print("Elements less than 3:", less_than_3)

arr[arr > 3]



Original Array: [1 2 3 4 5]
Elements greater than 3: [False False False  True  True]
Elements less than 3: [ True  True False False False]


array([4, 5])